# Generated by Django 5.1.2 on 2024-11-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_contactinfo_herosection_inquiry_portfolio_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='subject',
            field=models.TextField(default='General Inquiry', max_length=55),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(upload_to='portfolio/'),
        ),
    ]
