# Generated by Django 5.1.2 on 2024-11-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_alter_inquiry_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='subject',
            field=models.CharField(max_length=55),
        ),
    ]
